# Generated by Django 4.0.4 on 2022-04-20 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_tasks_delete_question'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tasks',
            new_name='Task',
        ),
    ]
