# Generated by Django 4.0.4 on 2022-04-20 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_rename_tasks_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='time',
            new_name='date',
        ),
    ]
