# Generated by Django 4.0.4 on 2022-04-21 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_rename_time_task_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_running',
            field=models.BooleanField(default=False),
        ),
    ]
