# Generated by Django 4.0.4 on 2022-04-25 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_task_is_running'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='account_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
