# Generated by Django 4.0.4 on 2022-04-25 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_task_account_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramBots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=200)),
                ('channel_name', models.CharField(max_length=200)),
                ('account_id', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
