# Generated by Django 4.0.4 on 2022-06-21 13:41

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0008_rename_telegrambots_telegrambot'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='time',
            field=models.TimeField(default=timezone.now(), verbose_name='Время'),
            preserve_default=False,
        ),
    ]
