# Generated by Django 4.0.4 on 2022-06-21 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0009_task_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='time',
            field=models.CharField(max_length=40, verbose_name='Время'),
        ),
    ]
