# Generated by Django 4.0.4 on 2022-06-21 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0010_alter_task_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='time',
        ),
    ]
